# Site settings
title: Travis Day
email: day.travis11@gmail.com
url: https://travisday.github.io
description: "I am Travis Day. This is a website about me; who I am and what I do"

# Color settings (hex-codes without the leading hash-tag) #000000
color:
  primary-dark: '#fff'
  links: '#CEA0DE'
  grey: '#444'

# Footer settings
footer:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Daytravis11
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/travisday

# Build settings
markdown: kramdown
permalink: pretty
